#!/usr/bin/env python
# coding: utf-8

# In[1]:


#3
import streamlit as st
st.header("'temperature conversion'")
st.write ("'**Change Celcius to Fahrenheit**'")
number = st.number_input("enter the value of temperature in Celcius")
C = ((number * (9/5))+32)
st.write (C,"°F")


# In[2]:


#1
kilometers = float(input("enter value in kilometers : "))
conv_fac = 0.621371
miles = kilometers * conv_fac
print('%0.2f kilometers is equal to %0.2f miles'%(kilometers,miles))


# In[14]:


#2
import time
start=time.time()
print(23*2.3)
end=time.time()
print(end-start)


# In[15]:


from timeit import default_timer as timer
start=time.time()
m=(5.96*1024)
print("mass of the earth is",m,"kg")
end=time.time()
print(end-start)


# In[ ]:




